### ISSUE TITLE
gobgp runs out of memory crashes gobgpd (rpc error)

### ISSUE THREAD

**Issue by jamesboswell** [osrg/gobgp#1127]
GoBGP cli crashes (out of memory) and gobgpd throws an rpc error and exits.
Triggering commands:  `/root/go/bin/gobgp global rib` or `/root/go/bin/gobgp n <peer> adj-in`

Environment:  Ubuntu 14.04 VM (2CPU 2GB RAM) in Openstack peered to a lab Juniper MX240

**FULL** routes 
up and running stats:

```
  Route statistics:
    Advertised:             0
    Received:          637069
    Accepted:          637069
root@gobgp:~#
root@gobgp:~#
root@gobgp:~# free
             total       used       free     shared    buffers     cached
Mem:       2049796    1783248     266548        368        916     636732
-/+ buffers/cache:    1145600     904196
Swap:            0          0          0
```

Go version and OS version

```
root@gobgp:~# go version
go version go1.7.1 linux/amd64
root@gobgp:~#
root@gobgp:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
root@gobgp:~#

```

GoBGP build pulled from master

```
go get -v github.com/osrg/gobgp/gobgp
go get github.com/osrg/gobgp/gobgpd
```

**Full output**

``````
root@gobgp:~# /root/go/bin/gobgp global rib
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xbedc00, 0x16)
    /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc48e7f0000, 0x5b30000, 0x0, 0x117bf58)
    /usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0x1162a40, 0x5b30000, 0x412d00)
    /usr/local/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0x1162a40, 0x2d91, 0x0)
    /usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0x1162a40, 0x2d91, 0x1)
    /usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0x1162a40, 0x2d91, 0x100000000, 0x7f81933cfab0)
    /usr/local/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
    /usr/local/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0x7f81a37b6dd8)
    /usr/local/go/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0x1162a40, 0x2d91, 0x10100000000, 0x4275be)
    /usr/local/go/src/runtime/mheap.go:580 +0x73
runtime.largeAlloc(0x5b21767, 0x458c01, 0xc488262000)
    /usr/local/go/src/runtime/malloc.go:774 +0x93
runtime.mallocgc.func1()
    /usr/local/go/src/runtime/malloc.go:669 +0x3e
runtime.systemstack(0xc42001a000)
    /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
    /usr/local/go/src/runtime/proc.go:1079

goroutine 70 [running]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc44ee738f8 sp=0xc44ee738f0
runtime.mallocgc(0x5b21767, 0xab4bc0, 0xb46b01, 0xc4717ac7d0)
    /usr/local/go/src/runtime/malloc.go:670 +0x903 fp=0xc44ee73998 sp=0xc44ee738f8
runtime.makeslice(0xab4bc0, 0x5b21767, 0x5b21767, 0xc488262000, 0x5b21762, 0x6512000)
    /usr/local/go/src/runtime/slice.go:57 +0x7b fp=0xc44ee739f0 sp=0xc44ee73998
google.golang.org/grpc.encode(0x1136840, 0x1179eb8, 0xb46b40, 0xc4717ac7d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /root/go/src/google.golang.org/grpc/rpc_util.go:285 +0x160 fp=0xc44ee73a88 sp=0xc44ee739f0
google.golang.org/grpc.(*Server).sendResponse(0xc4201c4140, 0x113a9e0, 0xc42dfcb560, 0xc4376b6b40, 0xb46b40, 0xc4717ac7d0, 0x0, 0x0, 0xc4717d367a, 0x0, ...)
    /root/go/src/google.golang.org/grpc/server.go:512 +0x91 fp=0xc44ee73b28 sp=0xc44ee73a88
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4201c4140, 0x113a9e0, 0xc42dfcb560, 0xc4376b6b40, 0xc4201396b0, 0x1126688, 0x0, 0x0, 0x0)
    /root/go/src/google.golang.org/grpc/server.go:637 +0x1050 fp=0xc44ee73d80 sp=0xc44ee73b28
google.golang.org/grpc.(*Server).handleStream(0xc4201c4140, 0x113a9e0, 0xc42dfcb560, 0xc4376b6b40, 0x0)
    /root/go/src/google.golang.org/grpc/server.go:769 +0x6b0 fp=0xc44ee73f40 sp=0xc44ee73d80
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc44e55fc40, 0xc4201c4140, 0x113a9e0, 0xc42dfcb560, 0xc4376b6b40)
    /root/go/src/google.golang.org/grpc/server.go:422 +0xab fp=0xc44ee73f78 sp=0xc44ee73f40
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc44ee73f80 sp=0xc44ee73f78
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /root/go/src/google.golang.org/grpc/server.go:423 +0xa3

goroutine 1 [select, 2 minutes]:
main.main()
    /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:204 +0x18bc

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 8 [select]:
github.com/eapache/channels.(*InfiniteChannel).infiniteBuffer(0xc42017edc0)
    /root/go/src/github.com/eapache/channels/infinite_channel.go:49 +0x28a
created by github.com/eapache/channels.NewInfiniteChannel
    /root/go/src/github.com/eapache/channels/infinite_channel.go:19 +0x1c5

goroutine 26 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f81a5f1eda8, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420224220, 0x72, 0xc42001e600, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420224220, 0x112f400, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc4202241c0, 0x0, 0x112d600, 0xc42017f280)
    /usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420112370, 0x1179eb8, 0xc4201226c0, 0xc42001e738)
    /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc420112370, 0x0, 0x1, 0xc42001e780)
    /usr/local/go/src/net/tcpsock.go:209 +0x49
github.com/osrg/gobgp/server.NewTCPListener.func1(0xc420112370, 0xc420122f60, 0xc420122f00, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/server.go:72 +0x40
created by github.com/osrg/gobgp/server.NewTCPListener
    /root/go/src/github.com/osrg/gobgp/server/server.go:83 +0x19e

goroutine 6 [syscall, 2 minutes]:
os/signal.signal_recv(0xc42001efa8)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 20 [select, 2 minutes, locked to thread]:
runtime.gopark(0xc4b7b8, 0x0, 0xbe1021, 0x6, 0x18, 0x2)
    /usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42001f730, 0x0, 0x18)
    /usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42001f730)
    /usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 21 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f81a5f1ef28, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420175250, 0x72, 0xc420039d00, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420175250, 0x112f400, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc4201751f0, 0x0, 0x112d600, 0xc42017f200)
    /usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420026400, 0xc420197620, 0xc420039e10, 0x81a7a0)
    /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc420026400, 0xc420082c5c, 0xc420039e00, 0x5e5510)
    /usr/local/go/src/net/tcpsock.go:209 +0x49
net/http.tcpKeepAliveListener.Accept(0xc420026400, 0xc4201975f0, 0xae9b00, 0x111da50, 0xb536c0)
    /usr/local/go/src/net/http/server.go:2608 +0x2f
net/http.(*Server).Serve(0xc420082c00, 0x1136900, 0xc420026400, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2273 +0x1ce
net/http.(*Server).ListenAndServe(0xc420082c00, 0xc420082c00, 0x0)
    /usr/local/go/src/net/http/server.go:2219 +0xb4
net/http.ListenAndServe(0xb19a99, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2351 +0xa0
main.main.func1(0xc4201c4000)
    /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:77 +0x54
created by main.main
    /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:78 +0x2f14

goroutine 22 [select]:
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc4201d6000)
    /root/go/src/github.com/osrg/gobgp/server/server.go:235 +0x49e
created by main.main
    /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:180 +0x44b

goroutine 23 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc42016d2ac)
    /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc42016d2a0)
    /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/osrg/gobgp/api.(*Server).Serve(0xc4201112c0, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/api/grpc_server.go:83 +0x164
main.main.func2(0xc4201112c0)
    /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:185 +0x2f
created by main.main
    /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:188 +0x498

goroutine 24 [chan receive, 2 minutes]:
github.com/osrg/gobgp/config.ReadConfigfileServe(0x7fff19b018ec, 0xb, 0xb1257e, 0x4, 0xc4201223c0)
    /root/go/src/github.com/osrg/gobgp/config/serve.go:66 +0x6fd
created by main.main
    /root/go/src/github.com/osrg/gobgp/gobgpd/main.go:199 +0x18ff

goroutine 10 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f81a5f1ee68, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201752c0, 0x72, 0xc4201e8d00, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201752c0, 0x112f400, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420175260, 0x0, 0x112d600, 0xc43c4a3b80)
    /usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420026408, 0x4385be, 0xc4201e8db0, 0x6c0329)
    /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc420026408, 0xc4ad28, 0xc4201c4140, 0x113ba60, 0xc44c188288)
    /usr/local/go/src/net/tcpsock.go:222 +0x49
google.golang.org/grpc.(*Server).Serve(0xc4201c4140, 0x1136100, 0xc420026408, 0x0, 0x0)
    /root/go/src/google.golang.org/grpc/server.go:348 +0x15a
github.com/osrg/gobgp/api.(*Server).Serve.func1(0xb00af2, 0x6)
    /root/go/src/github.com/osrg/gobgp/api/grpc_server.go:72 +0x11c
created by github.com/osrg/gobgp/api.(*Server).Serve
    /root/go/src/github.com/osrg/gobgp/api/grpc_server.go:81 +0x138

goroutine 27 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f81a5f1ece8, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420224290, 0x72, 0xc420021600, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420224290, 0x112f400, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420224230, 0x0, 0x112d600, 0xc42017f2a0)
    /usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420112378, 0xc420021508, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc420112378, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock.go:209 +0x49
github.com/osrg/gobgp/server.NewTCPListener.func1(0xc420112378, 0xc420122fc0, 0xc420122f00, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/server.go:72 +0x40
created by github.com/osrg/gobgp/server.NewTCPListener
    /root/go/src/github.com/osrg/gobgp/server/server.go:83 +0x19e

goroutine 53 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).established(0xc42007a750, 0x0, 0xc420023eb0, 0xc420023f68)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:1157 +0x952
github.com/osrg/gobgp/server.(*FSMHandler).loop.func1(0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:1229 +0x146
gopkg.in/tomb%2ev2.(*Tomb).run(0xc42007a750, 0xc42017f780)
    /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
    /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0xd0

goroutine 30 [select, 2 minutes]:
github.com/osrg/gobgp/server.(*FSM).connectLoop(0xc4201268c0, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:357 +0x333
github.com/osrg/gobgp/server.(*FSM).(github.com/osrg/gobgp/server.connectLoop)-fm(0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:203 +0x2a
gopkg.in/tomb%2ev2.(*Tomb).run(0xc4201268c0, 0xc42024c0a0)
    /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
    /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0xd0

goroutine 55 [runnable]:
syscall.Syscall(0x0, 0x8, 0xc45c0e04e0, 0x13, 0x13, 0x13, 0x0)
    /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc45c0e04e0, 0x13, 0x13, 0x72, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x8, 0xc45c0e04e0, 0x13, 0x13, 0xffffffffffffff01, 0x112f400, 0xc4200101f0)
    /usr/local/go/src/syscall/syscall_unix.go:161 +0x49
net.(*netFD).Read(0xc420175340, 0xc45c0e04e0, 0x13, 0x13, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/fd_unix.go:239 +0x10f
net.(*conn).Read(0xc4201123e0, 0xc45c0e04e0, 0x13, 0x13, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:173 +0x70
io.ReadAtLeast(0x112cd00, 0xc4201123e0, 0xc45c0e04e0, 0x13, 0x13, 0x13, 0xbc4720, 0xc420175400, 0x112cd00)
    /usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x112cd00, 0xc4201123e0, 0xc45c0e04e0, 0x13, 0x13, 0x13, 0xc420175490, 0xc4201e4bf3)
    /usr/local/go/src/io/io.go:325 +0x58
github.com/osrg/gobgp/server.readAll(0x113ba60, 0xc4201123e0, 0x13, 0x1, 0xc42453eba0, 0x0, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:566 +0xb8
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageWithError(0xc42007a750, 0x0, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:582 +0x87
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageloop(0xc42007a750, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:1130 +0x2f
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.recvMessageloop)-fm(0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:1145 +0x2a
gopkg.in/tomb%2ev2.(*Tomb).run(0xc42007a750, 0xc42016d770)
    /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
    /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0xd0

goroutine 51 [select, 2 minutes]:
github.com/eapache/channels.(*InfiniteChannel).infiniteBuffer(0xc42017f6a0)
    /root/go/src/github.com/eapache/channels/infinite_channel.go:49 +0x28a
created by github.com/eapache/channels.NewInfiniteChannel
    /root/go/src/github.com/eapache/channels/infinite_channel.go:19 +0x1c5

goroutine 52 [chan receive, 2 minutes]:
github.com/osrg/gobgp/server.(*FSMHandler).loop(0xc42007a750, 0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:1238 +0x156
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:396 +0x2a
gopkg.in/tomb%2ev2.(*Tomb).run(0xc4201268c0, 0xc42016d6e0)
    /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
    /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0xd0

goroutine 54 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).sendMessageloop(0xc42007a750, 0xc4201268c0, 0xc42005f140)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:1100 +0x493
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.sendMessageloop)-fm(0x0, 0x0)
    /root/go/src/github.com/osrg/gobgp/server/fsm.go:1143 +0x2a
gopkg.in/tomb%2ev2.(*Tomb).run(0xc42007a750, 0xc42016d760)
    /root/go/src/gopkg.in/tomb.v2/tomb.go:153 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
    /root/go/src/gopkg.in/tomb.v2/tomb.go:149 +0xd0

goroutine 68 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f81a5f1eb68, 0x72, 0x9)
    /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc44dfadfe0, 0x72, 0xc4200348e8, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc44dfadfe0, 0x112f400, 0xc4200101f0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc44dfadf80, 0xc44ea30000, 0x8000, 0x8000, 0x0, 0x112f400, 0xc4200101f0)
    /usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc44c188288, 0xc44ea30000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc447061380)
    /usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc447061380, 0xc44e0e27b8, 0x9, 0x9, 0x4451c0, 0xc44e55fcf0, 0x0)
    /usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x112ba80, 0xc447061380, 0xc44e0e27b8, 0x9, 0x9, 0x9, 0xc420034af8, 0x459220, 0xc420d3d280)
    /usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x112ba80, 0xc447061380, 0xc44e0e27b8, 0x9, 0x9, 0xc44e55fcf0, 0x0, 0x1)
    /usr/local/go/src/io/io.go:325 +0x58
golang.org/x/net/http2.readFrameHeader(0xc44e0e27b8, 0x9, 0x9, 0x112ba80, 0xc447061380, 0x0, 0xc400000000, 0xc420034c90, 0x8633c9)
    /root/go/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc44e0e2780, 0xb, 0xb, 0x0, 0x0)
    /root/go/src/golang.org/x/net/http2/frame.go:464 +0xa4
google.golang.org/grpc/transport.(*framer).readFrame(0xc449e30ed0, 0xc449e31920, 0xc449e31920, 0x0, 0x0)
    /root/go/src/google.golang.org/grpc/transport/http_util.go:508 +0x2f
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc42dfcb560, 0xc449e31020)
    /root/go/src/google.golang.org/grpc/transport/http2_server.go:260 +0x200
google.golang.org/grpc.(*Server).serveStreams(0xc4201c4140, 0x113a9e0, 0xc42dfcb560)
    /root/go/src/google.golang.org/grpc/server.go:424 +0x160
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc4201c4140, 0x113ba60, 0xc44c188288, 0x0, 0x0)
    /root/go/src/google.golang.org/grpc/server.go:411 +0x3da
google.golang.org/grpc.(*Server).handleRawConn(0xc4201c4140, 0x113ba60, 0xc44c188288)
    /root/go/src/google.golang.org/grpc/server.go:388 +0x470
created by google.golang.org/grpc.(*Server).Serve
    /root/go/src/google.golang.org/grpc/server.go:357 +0x1a9

goroutine 69 [select, 1 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc42dfcb560)
    /root/go/src/google.golang.org/grpc/transport/http2_server.go:673 +0x69c
created by google.golang.org/grpc/transport.newHTTP2Server
    /root/go/src/google.golang.org/grpc/transport/http2_server.go:139 +0x767
2016/09/30 17:54:17 transport: http2Client.notifyError got notified that the client transport was broken EOF.
rpc error: code = 13 desc = transport is closing
[1]+  Exit 2                  sudo -E /root/go/bin/gobgpd -f gobgpd.conf
root@gobgp:~#````
``````

**Comment by jamesboswell** [comment]
FYI BIRD is able to page through the entire table without issue.

**Comment by ishidawataru** [comment]
memory consumption is not a priority in this project. please allocate more memory to your VM or you could execute gobgp cli outside the vm (maybe on the host machine) by using `-u` option.

**Comment by devicenull** [comment]
How much memory should gobgp be using to receive a full table?

**Comment by fujita** [comment]
The memory usage is supposed to be improved with the current master but I'm not sure 2GB is enough.

**Comment by jamesboswell** [comment]
@fujita  I will give current master a  trial.   The VM can receive the full table no problem.    Problem arises when the CLI `gobgp` is instructed to look at all prefixes, this triggers a out-of-memory (OOM).   It does not appear to do any paging of the table.

Looking at individual prefixes does not trigger the OOM.    Yes 2GB VM isn't so realistic.   I do think it would be good to keep memory constraints in mind and handle more gracefully.   Having the `gobgpd` daemon crash because of a CLI command  is not optimal.

**Comment by fujita** [comment]
CLI temporarily uses lots of memory for optimal speed of showing routes mainly because people complained that CLI was too slow. Agreed that having such gracefully but I don't know how.

**Comment by cstockton** [comment]
@jamesboswell If you would like you could test https://github.com/osrg/gobgp/pull/1334 and see if it fixes your memory issues? Note there may be a issue as the CI fails but I think this should improve your use case for CLI as well.

**Comment by fujita** [comment]
The latest master should be fine. Please try.
