### ISSUE TITLE
Ruby gRPC client fails with "Enum value '_' does not start with an uppercase letter as is required for Ruby constants"

### ISSUE THREAD

**Issue by codeout** [osrg/gobgp#1718]
I have tried to connect ruby grpc client to gobgpd, but it failed with a following error.
Could you give some advice on this?

```shell
$ GOBGP_API=$GOPATH/src/github.com/osrg/gobgp/api
$ protoc -I $GOBGP_API --ruby_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_tools_ruby_protoc_plugin` $GOBGP_API/gobgp.proto
$ ruby -I. foo.rb
Traceback (most recent call last):
	5: from foo.rb:1:in `<main>'
	4: from /Users/koji/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /Users/koji/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /Users/koji/darwin/tmp/gobgp_performance/gobgp_pb.rb:868:in `<top (required)>'
	1: from /Users/koji/darwin/tmp/gobgp_performance/gobgp_pb.rb:1048:in `<module:Gobgpapi>'
/Users/koji/darwin/tmp/gobgp_performance/gobgp_pb.rb:1048:in `enummodule': Enum value '_' does not start with an uppercase letter as is required for Ruby constants. (TypeError)
```

## Ruby Client

```ruby
# foo.rb

require 'gobgp_pb'
require 'gobgp_services_pb'

stub = Gobgpapi::GobgpApi::Stub.new('localhost:50051', :this_channel_is_insecure)
```

## Just for testing

A patch below just works fine.

```diff
--- a/api/gobgp.proto
+++ b/api/gobgp.proto
@@ -83,7 +83,7 @@ service GobgpApi {

 // Constants for address families
 enum Family {
-  _ = 0;
+  RESERVED = 0;
   IPv4 = 65537;
   IPv6 = 131073;
   IPv4_MC = 65538;
```

**Comment by fujita** [comment]
Thanks for the report and a fix! The above fix looks fine to me. Can you create a pull request?
