### ISSUE TITLE
panic: runtime error when advertise a Inclusive Multicast Ethernet Tag Route

### ISSUE THREAD

**Issue by chenghit** [osrg/gobgp#1918]
Version 1.33 
[gobgp testing.zip](https://github.com/osrg/gobgp/files/2705829/gobgp.testing.zip)
add an evpn multicast route fail with below error:

chengc2@ubuntu:~$ cd $GOPATH/bin
chengc2@ubuntu:~/go/bin$ gobgp global rib -a evpn add multicast 10.15.0.5 etag 0 rd 50200:1 rt 50200:1 encap vxlan pmsi ingress-repl 50200 10.15.0.5                               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5f4456]

goroutine 1 [running]:
github.com/osrg/gobgp/packet/bgp.NewPathAttributePmsiTunnel(0x400000, 0x0, 0x0, 0x457650)
        /home/fujita/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:8381 +0x26
github.com/osrg/gobgp/packet/bgp.ParsePmsiTunnel(0xc42013e9b0, 0x3, 0x5, 0x7f235c8b1000, 0x0, 0x405b9b)
        /home/fujita/go/src/github.com/osrg/gobgp/packet/bgp/bgp.go:8403 +0x5c
github.com/osrg/gobgp/gobgp/cmd.extractPmsiTunnel(0xc42013e900, 0xe, 0x10, 0xc42013e900, 0xe, 0x10, 0x0, 0x0, 0x0, 0x0)
        /home/fujita/go/src/github.com/osrg/gobgp/gobgp/cmd/global.go:1020 +0xa3
github.com/osrg/gobgp/gobgp/cmd.ParsePath(0x190046, 0xc42013e900, 0xe, 0x10, 0xc4200db058, 0x406357, 0xc420001980)
        /home/fujita/go/src/github.com/osrg/gobgp/gobgp/cmd/global.go:1097 +0x1d3
github.com/osrg/gobgp/gobgp/cmd.modPath(0xb993e6, 0x6, 0x0, 0x0, 0xb9732e, 0x3, 0xc42013e900, 0xe, 0x10, 0xc4201a16e0, ...)
        /home/fujita/go/src/github.com/osrg/gobgp/gobgp/cmd/global.go:1280 +0x8c
github.com/osrg/gobgp/gobgp/cmd.NewGlobalCmd.func3(0xc4200edd40, 0xc42013e900, 0xe, 0x10)
        /home/fujita/go/src/github.com/osrg/gobgp/gobgp/cmd/global.go:1562 +0x79
github.com/osrg/gobgp/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200edd40, 0xc42013e600, 0x10, 0x10, 0xc4200edd40, 0xc42013e600)
        /home/fujita/go/src/github.com/osrg/gobgp/vendor/github.com/spf13/cobra/command.go:653 +0x2a2
github.com/osrg/gobgp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200ed680, 0xc4201e0b40, 0xc4201e0d80, 0xc4201e1680)
        /home/fujita/go/src/github.com/osrg/gobgp/vendor/github.com/spf13/cobra/command.go:728 +0x2d4
github.com/osrg/gobgp/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200ed680, 0xc420086058, 0x0)
        /home/fujita/go/src/github.com/osrg/gobgp/vendor/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
        /home/fujita/go/src/github.com/osrg/gobgp/gobgp/main.go:33 +0x6e

Please find the attached conf file and capture file. Could you give me some idea? Many thanks.

**Comment by fujita** [comment]
I can't reproduce this with the latest master. Looks like the above command succeeded and the path was installed.

```
fujitanombp:gobgp fujita$ ./cmd/gobgp/gobgp g r -a evpn
   Network                                            Labels     Next Hop             AS_PATH              Age        Attrs
*> [type:multicast][rd:50200:1][etag:0][ip:10.15.0.5]            0.0.0.0                                   00:01:05   [{Origin: ?} {Extcomms: [50200:1], [VXLAN]} {Pmsi: type: ingress-repl, label: 50200, tunnel-id: 10.15.0.5}]
```

**Comment by chenghit** [comment]
Hi fujita,

Thank you for your response. I rebuilt my test environment using centos7+golang1.11.4+gobgp1.33, but the panic issue still exists. Could you let me know what your environment is?

**Comment by fujita** [comment]
Please try the current master branch instead of 1.33.

**Comment by chenghit** [comment]
> Please try the current master branch instead of 1.33.

Many thanks fujita. But forgive my ignorance please, could you let me know where I can download the current master branch? I didn't find it on https://github.com/osrg/gobgp/tags

**Comment by fujita** [comment]
You need to build from the source code. If you don't know how, please wait for the next release. It will be released in a week.
