### ISSUE TITLE
sigsegv when providing port number for neighbor as part of neighbor-address

### ISSUE THREAD

**Issue by Habbie** [osrg/gobgp#2296]
# this works

```
[global.config]
  as = 65422
  router-id = "192.168.255.1"
  port = 1790
  local-address-list = ["127.0.0.1"]

[[neighbors]]
  [neighbors.config]
    neighbor-address = "127.0.0.1"
    peer-as = 65001
```

```
{"level":"info","msg":"gobgpd started","time":"2020-06-15T16:57:18+02:00"}
{"Topic":"Config","level":"info","msg":"Finished reading the config file","time":"2020-06-15T16:57:18+02:00"}
{"level":"info","msg":"Peer 127.0.0.1 is added","time":"2020-06-15T16:57:18+02:00"}
{"Topic":"Peer","level":"info","msg":"Add a peer configuration for:127.0.0.1","time":"2020-06-15T16:57:18+02:00"}
```

# this crashes
```
[global.config]
  as = 65422
  router-id = "192.168.255.1"
  port = 1790
  local-address-list = ["127.0.0.1"]

[[neighbors]]
  [neighbors.config]
    neighbor-address = "127.0.0.1:1791"
    peer-as = 65001
```

```
{"level":"info","msg":"gobgpd started","time":"2020-06-15T16:57:55+02:00"}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f6edd663360]

runtime stack:
runtime.throw(0xd77ca6, 0x2a)
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/signal_unix.go:679 +0x46a

goroutine 26 [syscall]:
runtime.cgocall(0xac7960, 0xc0000695c0, 0xc00011e1b0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/cgocall.go:133 +0x5b fp=0xc000069590 sp=0xc000069558 pc=0x403ecb
net._C2func_getaddrinfo(0xc000117f70, 0x0, 0xc00030be90, 0xc00011e1b0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55 fp=0xc0000695c0 sp=0xc000069590 pc=0x5cde65
net.cgoLookupIPCNAME.func1(0xc000117f70, 0xf, 0xf, 0xc00030be90, 0xc00011e1b0, 0x45130f, 0xc0000696a0, 0x5d1242)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/cgo_unix.go:161 +0xd2 fp=0xc000069608 sp=0xc0000695c0 pc=0x5d38c2
net.cgoLookupIPCNAME(0xd563a4, 0x2, 0xc0001179a0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/cgo_unix.go:161 +0x183 fp=0xc000069718 sp=0xc000069608 pc=0x5cf2f3
net.cgoIPLookup(0xc00010fda0, 0xd563a4, 0x2, 0xc0001179a0, 0xe)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/cgo_unix.go:218 +0x67 fp=0xc0000697b8 sp=0xc000069718 pc=0x5cfa27
runtime.goexit()
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000697c0 sp=0xc0000697b8 pc=0x468011
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/cgo_unix.go:228 +0xc7

goroutine 1 [select]:
net.(*Resolver).lookupIPAddr(0x15f87e0, 0xe927e0, 0xc000036100, 0xd563a4, 0x2, 0xc0001179a0, 0xe, 0xc00030b860, 0xc000124f00, 0x1, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/lookup.go:274 +0x664
net.(*Resolver).internetAddrList(0x15f87e0, 0xe927e0, 0xc000036100, 0xd563a4, 0x2, 0xc0001179a0, 0xe, 0x0, 0x0, 0x0, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/ipsock.go:280 +0x4da
net.ResolveIPAddr(0xd563a4, 0x2, 0xc0001179a0, 0xe, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/iprawsock.go:90 +0xf5
github.com/osrg/gobgp/internal/pkg/config.setDefaultNeighborConfigValuesWithViper(0xc000326c00, 0xc00014b080, 0xc0002b1900, 0x0, 0x0, 0x0)
	/home/runner/work/gobgp/gobgp/internal/pkg/config/default.go:144 +0x1500
github.com/osrg/gobgp/internal/pkg/config.setDefaultConfigValuesWithViper(0xc000327260, 0xc0002b1900, 0xc0002b1900, 0x0)
	/home/runner/work/gobgp/gobgp/internal/pkg/config/default.go:461 +0xea1
github.com/osrg/gobgp/internal/pkg/config.ReadConfigfile(0x7ffc4077e30a, 0xc, 0xc66e8c, 0x4, 0x2, 0x0, 0x0)
	/home/runner/work/gobgp/gobgp/internal/pkg/config/serve.go:38 +0x23a
github.com/osrg/gobgp/pkg/config.ReadConfigFile(...)
	/home/runner/work/gobgp/gobgp/pkg/config/config.go:19
main.main()
	/home/runner/work/gobgp/gobgp/cmd/gobgpd/main.go:173 +0x428

goroutine 18 [chan receive]:
main.init.0.func1()
	/home/runner/work/gobgp/gobgp/cmd/gobgpd/util.go:37 +0xbe
created by main.init.0
	/home/runner/work/gobgp/gobgp/cmd/gobgpd/util.go:34 +0x35

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/opt/hostedtoolcache/go/1.14.3/x64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/opt/hostedtoolcache/go/1.14.3/x64/src/os/signal/signal.go:127 +0x44

goroutine 21 [runnable]:
net.sockaddrToTCP(0xe7d220, 0xc000194120, 0xc000194120, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/tcpsock_posix.go:16 +0x1ea
net.(*netFD).listenStream(0xc0001be000, 0xe97200, 0xc00018a5a0, 0x1000, 0x0, 0x0, 0xa)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/sock_posix.go:203 +0x2c2
net.socket(0xe927e0, 0xc000036100, 0xd5673d, 0x3, 0x2, 0x1, 0x0, 0x0, 0xe97200, 0xc00018a5a0, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/sock_posix.go:57 +0x2a1
net.internetSocket(0xe927e0, 0xc000036100, 0xd5673d, 0x3, 0xe97200, 0xc00018a5a0, 0x0, 0x0, 0x1, 0x0, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/ipsock_posix.go:141 +0x141
net.(*sysListener).listenTCP(0xc00007de80, 0xe927e0, 0xc000036100, 0xc00018a5a0, 0xe85b20, 0xc00018a5a0, 0x3)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/tcpsock_posix.go:168 +0xb7
net.(*ListenConfig).Listen(0xc00007df18, 0xe927e0, 0xc000036100, 0xd5673d, 0x3, 0xc6ee99, 0xe, 0xc000196000, 0x0, 0x0, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/dial.go:637 +0x614
net.Listen(0xd5673d, 0x3, 0xc6ee99, 0xe, 0xe0, 0xd43200, 0x1, 0xc000196000)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/dial.go:707 +0x80
net/http.(*Server).ListenAndServe(0xc000196000, 0xc000196000, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2826 +0x72
net/http.ListenAndServe(...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:3086
main.main.func1(0xc0002da000)
	/home/runner/work/gobgp/gobgp/cmd/gobgpd/main.go:89 +0x7d
created by main.main
	/home/runner/work/gobgp/gobgp/cmd/gobgpd/main.go:88 +0x19ae

goroutine 22 [semacquire]:
sync.runtime_Semacquire(0xc00020a028)
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00020a020)
	/opt/hostedtoolcache/go/1.14.3/x64/src/sync/waitgroup.go:130 +0x64
github.com/osrg/gobgp/pkg/server.(*server).serve(0xc000122d60, 0x0, 0x0)
	/home/runner/work/gobgp/gobgp/pkg/server/grpc_server.go:100 +0x31b
github.com/osrg/gobgp/pkg/server.NewBgpServer.func1(0xc000122d60)
	/home/runner/work/gobgp/gobgp/pkg/server/server.go:163 +0x2f
created by github.com/osrg/gobgp/pkg/server.NewBgpServer
	/home/runner/work/gobgp/gobgp/pkg/server/server.go:162 +0x524

goroutine 23 [select]:
reflect.rselect(0xc0000463c0, 0x3, 0x3, 0xc0000463c0, 0x203000)
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/select.go:544 +0x38a
reflect.Select(0xc0000ca2c0, 0x3, 0x3, 0xc0000ca2c0, 0x0, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/reflect/value.go:2229 +0x170
github.com/osrg/gobgp/pkg/server.(*BgpServer).Serve(0xc000170d80)
	/home/runner/work/gobgp/gobgp/pkg/server/server.go:396 +0x2cd
created by main.main
	/home/runner/work/gobgp/gobgp/cmd/gobgpd/main.go:153 +0x380

goroutine 50 [IO wait]:
internal/poll.runtime_pollWait(0x7f6ee409d080, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00020e098, 0x72, 0x0, 0x0, 0xd595e2)
	/opt/hostedtoolcache/go/1.14.3/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00020e080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00020e080, 0xc000234008, 0xc0002f9d88, 0xc000234000)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000208040, 0xc000068528, 0xc000234000, 0xc000234088)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000208040, 0xc0002c9cb0, 0xc0002f9d88, 0xc000234088, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/tcpsock.go:261 +0x64
google.golang.org/grpc.(*Server).Serve(0xc0002d4640, 0xe8fae0, 0xc000208040, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.5.1/server.go:444 +0x183
github.com/osrg/gobgp/pkg/server.(*server).serve.func1(0xe8fae0, 0xc000208040)
	/home/runner/work/gobgp/gobgp/pkg/server/grpc_server.go:89 +0x8d
created by github.com/osrg/gobgp/pkg/server.(*server).serve
	/home/runner/work/gobgp/gobgp/pkg/server/grpc_server.go:98 +0x2f8

goroutine 25 [select]:
net.cgoLookupIP(0xe927a0, 0xc000124f40, 0xd563a4, 0x2, 0xc0001179a0, 0xe, 0x0, 0x0, 0xc0000694f8, 0x48125f, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/cgo_unix.go:229 +0x195
net.(*Resolver).lookupIP(0x15f87e0, 0xe927a0, 0xc000124f40, 0xd563a4, 0x2, 0xc0001179a0, 0xe, 0x0, 0x938000, 0xc00016a480, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/lookup_unix.go:96 +0x187
net.glob..func1(0xe927a0, 0xc000124f40, 0xc00030c430, 0xd563a4, 0x2, 0xc0001179a0, 0xe, 0x0, 0x0, 0xc000069780, ...)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.3/x64/src/net/lookup.go:268 +0xb9
internal/singleflight.(*Group).doCall(0x15f87f0, 0xc000126e60, 0xc00011a7a0, 0x11, 0xc000124f80)
	/opt/hostedtoolcache/go/1.14.3/x64/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.14.3/x64/src/internal/singleflight/singleflight.go:88 +0x2bc
```

**Comment by serejkus** [comment]
@Habbie what gobgp version are you using? It looks like it just reports an error in master (and I've checked v2.14 too):
```
serejkus@MacBook-Pro-Sergej-2 gobgp % cat buggy.toml
[global.config]
  as = 65422
  router-id = "192.168.255.1"
  port = 1790
  local-address-list = ["127.0.0.1"]

[[neighbors]]
  [neighbors.config]
    neighbor-address = "127.0.0.1:1791"
    peer-as = 65001
serejkus@MacBook-Pro-Sergej-2 gobgp % go run ./cmd/gobgpd -f buggy.toml -d
{"Error":"lookup 127.0.0.1:1791: no such host","Topic":"Config","level":"fatal","msg":"Can't read config file buggy.toml","time":"2020-06-26T23:39:37+03:00"}
exit status 1
```

**Comment by Habbie** [comment]
Sorry for not mentioning that. I'm pretty sure this was with 2.17 binaries downloaded from the Releases tab. I'll do some more digging - given what the traces look like, I would not be surprised if a difference between your MacOS libc and my Debian libc matters.

**Comment by Habbie** [comment]
Yes, amd64 2.17 binaries from the release tab, on Debian Buster.

**Comment by Habbie** [comment]
A local build on Debian Buster behaves like you said - a decent error. The golang version is '1.11.6-1+deb10u3'. So, the problem is somehow related to how the release binaries are built.

**Comment by fujita** [comment]
The release binary is a static binary. You can see [the compile options](https://github.com/osrg/gobgp/blob/master/.goreleaser.yml) but looks like that it's not enough. Still glibc is used and the error handling about resolving an address causes this bug.
https://github.com/osrg/gobgp/pull/2300

**Comment by fujita** [comment]
Can you try v2.18.0 binary?

https://github.com/osrg/gobgp/releases/tag/v2.18.0

**Comment by Habbie** [comment]
> Can you try v2.18.0 binary?

`{"Error":"lookup 127.0.0.1:1791: no such host","Topic":"Config","level":"fatal","msg":"Can't read config file gobgp.conf","time":"2020-07-01T19:41:10+02:00"}`


no crash!

**Comment by Habbie** [comment]
thanks!
