### ISSUE TITLE
Unexpected crash for master build

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#2326]
Hello!

During my tests for binary attrs I did something with flow spec NLRI and crashed gobgp build from master branch: https://github.com/fujita/gobgp/commit/98b017d1ade751b3c2323fbdebe631e3454ebde0
```
panic: runtime error: index out of range [16] with length 4

goroutine 12 [running]:
github.com/osrg/gobgp/pkg/packet/bgp.(*IPAddrPrefixDefault).decodePrefix(0xc0004262a0, 0xc0001f663f, 0x1b, 0x1b, 0x486, 0x0, 0x0)
  /home/odintsov/gobgp_master/pkg/packet/bgp/bgp.go:1195 +0x209
github.com/osrg/gobgp/pkg/packet/bgp.(*IPAddrPrefix).DecodeFromBytes(0xc0004262a0, 0xc0001f663e, 0x1c, 0x1c, 0x0, 0x0, 0x0, 0x1, 0xc00011ce80)
  /home/odintsov/gobgp_master/pkg/packet/bgp/bgp.go:1247 +0x1ad
github.com/osrg/gobgp/pkg/packet/bgp.(*flowSpecPrefix).DecodeFromBytes(0xc00011ce80, 0xc0001f663d, 0x1d, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/odintsov/gobgp_master/pkg/packet/bgp/bgp.go:3911 +0xa0
github.com/osrg/gobgp/pkg/packet/bgp.(*FlowSpecNLRI).decodeFromBytes(0xc000126ac0, 0x10085, 0xc0001f663d, 0x1d, 0x1d, 0x0, 0x0, 0x0, 0xdfc3c0, 0xc000126a00)
  /home/odintsov/gobgp_master/pkg/packet/bgp/bgp.go:4441 +0x2ff
github.com/osrg/gobgp/pkg/packet/bgp.(*FlowSpecIPv4Unicast).DecodeFromBytes(0xc000126ac0, 0xc0001f6630, 0x2a, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/odintsov/gobgp_master/pkg/packet/bgp/bgp.go:4669 +0x91
github.com/osrg/gobgp/internal/pkg/apiutil.getNLRI(0x10085, 0xc0001f6630, 0x2a, 0x2a, 0x1000000000000, 0x0, 0x3, 0xc00018bca8)
  /home/odintsov/gobgp_master/internal/pkg/apiutil/util.go:87 +0xae
github.com/osrg/gobgp/internal/pkg/apiutil.GetNativeNlri(0xc0001c3ba0, 0x5, 0x3, 0x7fef6a95d758, 0x0)
  /home/odintsov/gobgp_master/internal/pkg/apiutil/util.go:98 +0x73
github.com/osrg/gobgp/pkg/server.api2Path(0xc000000000, 0xc0001c3ba0, 0xc0001be700, 0x60, 0xe0, 0xc43e80)
  /home/odintsov/gobgp_master/pkg/server/grpc_server.go:273 +0x57
github.com/osrg/gobgp/pkg/server.(*BgpServer).AddPath.func1(0x493881, 0xb47640)
  /home/odintsov/gobgp_master/pkg/server/server.go:1995 +0x54
github.com/osrg/gobgp/pkg/server.(*BgpServer).handleMGMTOp(0xc0000dfb00, 0xc00011ce20)
  /home/odintsov/gobgp_master/pkg/server/server.go:218 +0x47
github.com/osrg/gobgp/pkg/server.(*BgpServer).Serve(0xc0000dfb00)
  /home/odintsov/gobgp_master/pkg/server/server.go:400 +0x6f2
created by main.main
  /home/odintsov/gobgp_master/cmd/gobgpd/main.go:153 +0x394
```

I have no good reproduce but I did it few times. I suppose my flow spec annoucne was malformed.

**Comment by fujita** [comment]
thanks for the report! I've pushed the fix.
https://github.com/osrg/gobgp/commit/0ac9ac9b2561dceb430e96b2a7973a1a05ab61a0

**Comment by pavel-odintsov** [comment]
Thank you so much!
