### ISSUE TITLE
gobgpd panic on empty MpReachNLRIAttribute

### ISSUE THREAD

**Issue by aelg** [osrg/gobgp#2330]
**Note: I think there are two separate panics here**

Panic 1
---
gobgpd panics when receiving an `AddPathRequest` with an empty `MpReachNLRIAttribute`

output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e90d9]

goroutine 10 [running]:
github.com/osrg/gobgp/internal/pkg/apiutil.ToRouteFamily(...)
	gobgp/internal/pkg/apiutil/util.go:124
github.com/osrg/gobgp/internal/pkg/apiutil.unmarshalAttribute(0xc000111020, 0x0, 0x1, 0xc0001592b0, 0x203000)
	gobgp/internal/pkg/apiutil/attribute.go:1509 +0x479
github.com/osrg/gobgp/internal/pkg/apiutil.UnmarshalPathAttributes(0xc00011a080, 0x1, 0x1, 0x0, 0x0, 0x5, 0x2, 0x17e3440)
	gobgp/internal/pkg/apiutil/attribute.go:1448 +0x105
github.com/osrg/gobgp/internal/pkg/apiutil.GetNativePathAttributes(0xc00015be10, 0x0, 0xc000111080, 0x0, 0x0, 0xc00011e1c0)
	gobgp/internal/pkg/apiutil/util.go:120 +0x325
github.com/osrg/gobgp/pkg/server.api2Path(0x0, 0xc00015be10, 0x0, 0x2, 0x16f4a40, 0xc000042360)
	gobgp/pkg/server/grpc_server.go:294 +0xb0
github.com/osrg/gobgp/pkg/server.(*BgpServer).AddPath.func1(0x109f109, 0x16db4e0)
	gobgp/pkg/server/server.go:1995 +0x54
github.com/osrg/gobgp/pkg/server.(*BgpServer).handleMGMTOp(0xc00018c900, 0xc00011c520)
	gobgp/pkg/server/server.go:218 +0x47
github.com/osrg/gobgp/pkg/server.(*BgpServer).Serve(0xc00018c900)
	gobgp/pkg/server/server.go:400 +0x735
created by main.main
	gobgp/cmd/gobgpd/main.go:153 +0x38f
```

Client to reproduce
```go
func crash(ctx context.Context, client api.GobgpApiClient) {

	nlri, _ := ptypes.MarshalAny(&api.IPAddressPrefix{})

	a, _ := ptypes.MarshalAny(&api.MpReachNLRIAttribute{})

	client.AddPath(ctx, &api.AddPathRequest{
		Path: &api.Path{
			Family:     &api.Family{Afi: api.Family_AFI_IP, Safi: api.Family_SAFI_UNICAST},
			Nlri:       nlri,
			Pattrs:     []*any.Any{a},
		},
	})
}
```

Panic 2
---
Adding Family to the attribute still panics
```go
func crash(ctx context.Context, client api.GobgpApiClient) {

	nlri, _ := ptypes.MarshalAny(&api.IPAddressPrefix{})

	a, _ := ptypes.MarshalAny(&api.MpReachNLRIAttribute{
		Family: &api.Family{Afi: api.Family_AFI_IP, Safi: api.Family_SAFI_FLOW_SPEC_UNICAST}, // <---- Added Family
	})

	client.AddPath(ctx, &api.AddPathRequest{
		Path: &api.Path{
			Family:     &api.Family{Afi: api.Family_AFI_IP, Safi: api.Family_SAFI_UNICAST},
			Nlri:       nlri,
			Pattrs:     []*any.Any{a},
		},
	})
}
```
Seems to produce a different panic

Log:
```
goroutine 10 [running]:
github.com/osrg/gobgp/pkg/server.api2Path(0x0, 0xc0002e0750, 0x0, 0x2, 0x16f4a40, 0xc000042360)
	gobgp/pkg/server/grpc_server.go:313 +0xd4c
github.com/osrg/gobgp/pkg/server.(*BgpServer).AddPath.func1(0x109f109, 0x16db4e0)
	gobgp/pkg/server/server.go:1995 +0x54
github.com/osrg/gobgp/pkg/server.(*BgpServer).handleMGMTOp(0xc00017c480, 0xc00000f220)
	gobgp/pkg/server/server.go:218 +0x47
github.com/osrg/gobgp/pkg/server.(*BgpServer).Serve(0xc00017c480)
	gobgp/pkg/server/server.go:400 +0x735
created by main.main
	gobgp/cmd/gobgpd/main.go:153 +0x38f
```

**Comment by fujita** [comment]
Thanks for the report! I fixed both bugs. Please try the current master.
