### ISSUE TITLE
GoBgp gRPC Java client is not working

### ISSUE THREAD

**Issue by Marty-Github** [osrg/gobgp#2587]
Hello,

I'm trying to implement gobgp grpc java client by means of gradle build tool.
Projects '[grpc-java](https://github.com/grpc/grpc-java)' and '[protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin)' are used as dependencies and plugin.
It's building and running with error:

_io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service apipb.GobgpApi
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at apipb.GobgpApiGrpc$GobgpApiBlockingStub.getBgp(GobgpApiGrpc.java:3033)
	at grpc.Client.build_path(Client.java:80)
	at grpc.Client.process(Client.java:123)
	at grpc.Client.main(Client.java:136)_
	
The *.proto  files  are taken from  [gobgp/api](https://github.com/osrg/gobgp/tree/master/api) .

The only example '[gobgp-grpc-java](https://github.com/ng-labo/gobgp-grpc-java)' I've found uses Maven tool and can't be built.
I use java [client's source code](https://github.com/ng-labo/gobgp-grpc-java/blob/master/src/main/java/gobgpapi/example/Client.java) from that example in my project.

My environment:
OS:		Windows 10  =>  WSL2  =>  Ubuntu 20.04
JDK:	java-11-openjdk (linux)

$>java -version
_openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)_

GoBgp service is installed under WSL2(Ubuntu 20.04) by command:
$>sudo apt-get -y install gobgpd

GoBgp service is runnig with configuration file taken from your '[Getting Started](https://github.com/osrg/gobgp/blob/master/docs/sources/getting-started.md)'.
GoBgp CLI is working well. All commands are executed.

The source code of my gobgp grpc java client project is in attachment.
Could you please clarify what's wrong with it.
Is there any working example of grpc java client for gobgp?

Thanks

= = = = = = = = = = = = = =  = = = = = = = = == = = = = =
   Gradle configuration
= = = = = = = = = = = = = =  = = = = = = = = == = = = = =

_plugins {
    id 'java'
    id 'com.google.protobuf' version '0.9.1'
}

group 'com.gobgp.grpc'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.grpc:grpc-protobuf:1.49.2'
    implementation 'io.grpc:grpc-stub:1.49.2'
    implementation 'io.grpc:grpc-all:1.49.2'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'

    runtimeOnly 'io.grpc:grpc-netty-shaded:1.49.2'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.21.7"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.49.2'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}_

[gobgp-grpc-client.zip](https://github.com/osrg/gobgp/files/9786340/gobgp-grpc-client.zip)

**Comment by ljluestc** [comment]
```

package grpc;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.StatusRuntimeException;
import apipb.GobgpApiGrpc;
import apipb.GetBgpRequest;
import apipb.GetBgpResponse;

public class Client {
    private final GobgpApiGrpc.GobgpApiBlockingStub blockingStub;

    public Client(String host, int port) {
        ManagedChannel channel = ManagedChannelBuilder.forAddress(host, port)
                .usePlaintext() // Use plaintext for simplicity; switch to TLS in production
                .build();
        blockingStub = GobgpApiGrpc.newBlockingStub(channel);
    }

    public void getBgp() {
        GetBgpRequest request = GetBgpRequest.newBuilder().build(); // Populate request as needed
        GetBgpResponse response;
        try {
            response = blockingStub.getBgp(request);
            System.out.println("BGPS: " + response.toString());
        } catch (StatusRuntimeException e) {
            System.err.println("RPC failed: " + e.getStatus());
            return;
        }
    }

    public static void main(String[] args) {
        Client client = new Client("localhost", 50051); // Replace with the correct host and port
        client.getBgp();
    }
}
```
