### ISSUE TITLE
Multiple crash found by fuzzing

### ISSUE THREAD

**Issue by 0x34d** [osrg/gobgp#2708]
PR: https://github.com/osrg/gobgp/pull/2707

### 1

file:  `gobgp/pkg/packet/rtr/rtr_test.go`

```go
func TestParseRTRbug(t *testing.T) {
	ParseRTR([]byte("0\x0400000000"))
}
```

run: `go test -run TestParseRTRbug 	$(pwd)/pkg/packet/rtr`

backtrace:
```log
--- FAIL: TestParseRTRbug (0.00s)
panic: runtime error: index out of range [10] with length 10 [recovered]
	panic: runtime error: index out of range [10] with length 10

goroutine 6 [running]:
testing.tRunner.func1.2({0x6439e0, 0xc00001e390})
	/usr/lib/golang/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1529 +0x39f
panic({0x6439e0, 0xc00001e390})
	/usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/osrg/gobgp/v3/pkg/packet/rtr.(*RTRIPPrefix).DecodeFromBytes(0x10?, {0xc00001a960?, 0xc00001a960?, 0x0?})
	/home/legion/0x34d/gobgp/pkg/packet/rtr/rtr.go:217 +0x18c
github.com/osrg/gobgp/v3/pkg/packet/rtr.ParseRTR({0xc00001a960, 0xa, 0xa})
	/home/legion/0x34d/gobgp/pkg/packet/rtr/rtr.go:390 +0x138
github.com/osrg/gobgp/v3/pkg/packet/rtr.TestParseRTRbug(0x0?)
	/home/legion/0x34d/gobgp/pkg/packet/rtr/rtr_test.go:127 +0x45
testing.tRunner(0xc0000d0820, 0x686448)
	/usr/lib/golang/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/osrg/gobgp/v3/pkg/packet/rtr	0.008s
FAIL
```

**Comment by fujita** [comment]
random bytes? However, GoBGP thought it was an Open Message and crashed.
