### ISSUE TITLE
 gobgp   CLI    can't   list  bgp-ls  rib 

### ISSUE THREAD

**Issue by tankII** [osrg/gobgp#2818]
When  I  success  setup  bgp-ls  neighbor   with   router   , and want   to  list  rib   info  of bgp-ls  ,  gobgp   CLI   throw   exception  . like  below :

[root@lab177  gobgp]# ./gobgp   global rib  -a ls
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/osrg/gobgp/v3/pkg/packet/bgp.(*LsTLVIPReachability).ToIPNet(0xc002b47de0, 0x1)
        /home/runner/work/gobgp/gobgp/pkg/packet/bgp/bgp.go:7092 +0x279
github.com/osrg/gobgp/v3/pkg/packet/bgp.(*LsPrefixDescriptor).ParseTLVs(0xc00074f6c8, {0xc002b47e00?, 0x2, 0x486ea5?}, 0x60?)
        /home/runner/work/gobgp/gobgp/pkg/packet/bgp/bgp.go:5502 +0x8d
github.com/osrg/gobgp/v3/pkg/packet/bgp.(*LsPrefixV6NLRI).String(0xc003bd51c0)
        /home/runner/work/gobgp/gobgp/pkg/packet/bgp/bgp.go:5694 +0xcd
github.com/osrg/gobgp/v3/pkg/packet/bgp.(*LsAddrPrefix).String(0xc003c6c500?)
        /home/runner/work/gobgp/gobgp/pkg/packet/bgp/bgp.go:9151 +0x2b
main.makeShowRouteArgs(0xc000261900, 0x430890?, {0x0?, 0xc00074f980?, 0x469e4e?}, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/runner/work/gobgp/gobgp/cmd/gobgp/neighbor.go:653 +0xba4
main.showRoute({0xc003c28000, 0x1454, 0xc000134000?}, 0x1, 0x40?, 0x0, 0x0, 0x0)
        /home/runner/work/gobgp/gobgp/cmd/gobgp/neighbor.go:663 +0xb4d
main.showNeighborRib({0xc8bac8, 0x6}, {0x0, 0x0}, {0xc000131e80, 0x0, 0x4})
        /home/runner/work/gobgp/gobgp/cmd/gobgp/neighbor.go:1040 +0xc05
main.showGlobalRib(...)
        /home/runner/work/gobgp/gobgp/cmd/gobgp/global.go:2000
main.newGlobalCmd.func2(0xc000288900?, {0xc000131e80?, 0x4?, 0x4?})
        /home/runner/work/gobgp/gobgp/cmd/gobgp/global.go:2302 +0x37
github.com/spf13/cobra.(*Command).execute(0xc000288900, {0xc000131e40, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000288300)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /home/runner/work/gobgp/gobgp/cmd/gobgp/main.go:32 +0xc5

anyone  use  gobgp   CLI   browse  rib of  bgp-ls   success  ?  or  command  is   not supported  for  bgp-ls  family  ?

**Comment by ljluestc** [comment]
```

import grpc
import gobgp_pb2
import gobgp_pb2_grpc
import attribute_pb2
from google.protobuf.any_pb2 import Any

def list_bgp_ls_rib():
    # Connect to GoBGP gRPC server
    channel = grpc.insecure_channel('localhost:50051')
    stub = gobgp_pb2_grpc.GobgpApiStub(channel)

    # Request BGP-LS RIB (AFI=16388, SAFI=71)
    request = gobgp_pb2.ListPathRequest(
        table_type=gobgp_pb2.GLOBAL,
        family=gobgp_pb2.Family(
            afi=gobgp_pb2.Family.AFI_LS,
            safi=gobgp_pb2.Family.SAFI_LS
        )
    )

    try:
        # Stream paths from the RIB
        responses = stub.ListPath(request)
        for response in responses:
            if not response.destination:
                continue
            for path in response.destination.paths:
                # Extract NLRI
                nlri_any = path.nlri
                nlri = attribute_pb2.LsAddrPrefix()
                nlri_any.Unpack(nlri)
                
                # Extract attributes
                attrs = []
                for attr_any in path.pattrs:
                    attr = attribute_pb2.PathAttribute()
                    attr_any.Unpack(attr)
                    attrs.append(attr)

                # Print NLRI and key attributes
                print(f"NLRI: {nlri}")
                print(f"Path Attributes: {attrs}")
                print(f"Source: {path.source_id}, AS: {path.source_asn}")
                print("-" * 50)

    except grpc.RpcError as e:
        print(f"gRPC Error: {e}")

if __name__ == '__main__':
    list_bgp_ls_rib()
```
