### ISSUE TITLE
gobgp segmentation fault when working with community

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#306]
Hello, Network Gurus!

I have broken your tool when plying with communities :( I'm so sorry about it.

I have created announce:
```bash
gobgp global rib add 10.33.1.0/24 -a ipv4
```

Then I have created blackhole community:
```bash
gobgp policy community add blackhole 65000:666
```

And enabled it for all exported prefixes:
```bash
gobgp neighbor 213.133.111.200 policy add export blackhole accept
```

After this operations source session goes away:
```bash
gobgpd
{"level":"info","msg":"Peer 213.133.111.200 is added","time":"2015-09-02T12:13:32+03:00"}
{"Key":"213.133.111.200","State":5,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2015-09-02T12:13:39+03:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x4f3a6c]

goroutine 11 [running]:
github.com/osrg/gobgp/server.(*LocalRib).setPolicy(0x0, 0xc82005cd80, 0xc8201fb1a0)
	/root/gofolder/src/github.com/osrg/gobgp/server/peer.go:415 +0x67c
github.com/osrg/gobgp/server.(*BgpServer).handleGrpc(0xc820059c00, 0xc8200f1310, 0x0, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:1500 +0x35d0
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc820059c00)
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:335 +0x2d09
created by main.main
	/root/gofolder/src/github.com/osrg/gobgp/gobgpd/main.go:145 +0x961

goroutine 1 [select]:
main.main()
	/root/gofolder/src/github.com/osrg/gobgp/gobgpd/main.go:165 +0x1955

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 13 [chan receive]:
github.com/osrg/gobgp/server.(*BgpServer).Serve.func1(0xc82001ad20)
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:145 +0x61
created by github.com/osrg/gobgp/server.(*BgpServer).Serve
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:164 +0x149

goroutine 8 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [select, locked to thread]:
runtime.gopark(0xb794a0, 0xc820026f28, 0xa60cc0, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026f28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 10 [chan receive]:
github.com/osrg/gobgp/config.ReadConfigfileServe(0xa712d0, 0xb, 0xc82001a780, 0xc82001a7e0)
	/root/gofolder/src/github.com/osrg/gobgp/config/serve.go:17 +0x60
created by main.main
	/root/gofolder/src/github.com/osrg/gobgp/gobgpd/main.go:142 +0x8f8

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7f46a0281d78, 0x72, 0xc82000a1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200147d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200147d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820014770, 0x0, 0x7f46a0281fb8, 0xc8201dec60)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028490, 0xc820039dc0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820028490, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc8200f0be0, 0x7f46a0281fe0, 0xc820028490, 0x0, 0x0)
	/root/gofolder/src/google.golang.org/grpc/server.go:198 +0x18a
github.com/osrg/gobgp/server.(*Server).Serve(0xc8201329d0, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/grpc_server.go:105 +0x296
created by main.main
	/root/gofolder/src/github.com/osrg/gobgp/gobgpd/main.go:149 +0x9a4

goroutine 14 [chan receive]:
github.com/osrg/gobgp/server.(*BgpServer).Serve.func2(0xc82001ad80)
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:169 +0x43
created by github.com/osrg/gobgp/server.(*BgpServer).Serve
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:172 +0x18c

goroutine 15 [IO wait]:
net.runtime_pollWait(0x7f46a0281ef8, 0x72, 0xc82000a1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200146f0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200146f0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820014690, 0x0, 0x7f46a0281fb8, 0xc82011b900)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028480, 0xc82001ade0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/osrg/gobgp/server.listenAndAccept.func1(0xc820028480, 0xc82001ade0)
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:121 +0x31
created by github.com/osrg/gobgp/server.listenAndAccept
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:128 +0x227

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7f46a0281e38, 0x72, 0xc82000a1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820014760, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820014760, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820014700, 0x0, 0x7f46a0281fb8, 0xc82011b4e0)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028488, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/osrg/gobgp/server.listenAndAccept.func1(0xc820028488, 0xc82001ade0)
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:121 +0x31
created by github.com/osrg/gobgp/server.listenAndAccept
	/root/gofolder/src/github.com/osrg/gobgp/server/server.go:128 +0x227

goroutine 18 [select]:
github.com/osrg/gobgp/server.(*FSM).connectLoop(0xc820077a40, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:244 +0x4f7
github.com/osrg/gobgp/server.(*FSM).(github.com/osrg/gobgp/server.connectLoop)-fm(0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:147 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820077a40, 0xc820132e50)
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 30 [chan receive]:
github.com/osrg/gobgp/server.(*FSMHandler).loop(0xc8200cb900, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:876 +0x14d
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:280 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820077a40, 0xc820133900)
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 31 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).established(0xc8200cb900, 0x51b73e)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:800 +0xfff
github.com/osrg/gobgp/server.(*FSMHandler).loop.func1(0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:867 +0xe3
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8200cb900, 0xc8201de060)
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 32 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).sendMessageloop(0xc8200cb900, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:746 +0x50e
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.sendMessageloop)-fm(0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:788 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8200cb900, 0xc8201339d0)
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 33 [IO wait]:
net.runtime_pollWait(0x7f46a0281cb8, 0x72, 0xc82000a1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820014ae0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820014ae0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820014a80, 0xc8201de620, 0x13, 0x13, 0x0, 0x7f46a027c050, 0xc82000a1b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200284d0, 0xc8201de620, 0x13, 0x13, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x7f46a02822a8, 0xc8200284d0, 0xc8201de620, 0x13, 0x13, 0x13, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7f46a02822a8, 0xc8200284d0, 0xc8201de620, 0x13, 0x13, 0x13, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
github.com/osrg/gobgp/server.readAll(0x7f46a02821f0, 0xc8200284d0, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:394 +0xd9
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageWithError(0xc8200cb900, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:402 +0x7a
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageloop(0xc8200cb900, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:778 +0x2d
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.recvMessageloop)-fm(0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/fsm.go:790 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8200cb900, 0xc8201339e0)
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/root/gofolder/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 43 [runnable]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8200714d0)
	/root/gofolder/src/google.golang.org/grpc/transport/http2_server.go:611 +0x629
created by google.golang.org/grpc/transport.newHTTP2Server
	/root/gofolder/src/google.golang.org/grpc/transport/http2_server.go:133 +0x852

goroutine 44 [IO wait]:
net.runtime_pollWait(0x7f46a0281bf8, 0x72, 0xc82000a1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82020ba30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020ba30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020b9d0, 0xc820071464, 0x9, 0x9, 0x0, 0x7f46a027c050, 0xc82000a1b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820028588, 0xc820071464, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x7f46a02822a8, 0xc820028588, 0xc820071464, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7f46a02822a8, 0xc820028588, 0xc820071464, 0x9, 0x9, 0x6da8579645415501, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
github.com/bradfitz/http2.readFrameHeader(0xc820071464, 0x9, 0x9, 0x7f46a02822a8, 0xc820028588, 0xa0000000, 0xc800000000, 0x0, 0x0)
	/root/gofolder/src/github.com/bradfitz/http2/frame.go:228 +0xa5
github.com/bradfitz/http2.(*Framer).ReadFrame(0xc820071440, 0x0, 0x0, 0x0, 0x0)
	/root/gofolder/src/github.com/bradfitz/http2/frame.go:373 +0xe6
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201fb260, 0x0, 0x0, 0x0, 0x0)
	/root/gofolder/src/google.golang.org/grpc/transport/http_util.go:445 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8200714d0, 0xc8201dec80)
	/root/gofolder/src/google.golang.org/grpc/transport/http2_server.go:249 +0x6be
google.golang.org/grpc.(*Server).Serve.func2(0x7f46a02823f0, 0xc8200714d0, 0xc8200f0be0)
	/root/gofolder/src/google.golang.org/grpc/server.go:229 +0x89
created by google.golang.org/grpc.(*Server).Serve
	/root/gofolder/src/google.golang.org/grpc/server.go:233 +0x733

goroutine 45 [chan receive]:
github.com/osrg/gobgp/server.(*Server).ModNeighborPolicy(0xc8201329d0, 0x7f46a0282fe0, 0xc8201fef50, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/server/grpc_server.go:319 +0x4e6
github.com/osrg/gobgp/api._Grpc_ModNeighborPolicy_Handler(0xa425e0, 0xc8201329d0, 0x7f46a0282768, 0xc820071560, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/api/gobgp.pb.go:1523 +0xdb
google.golang.org/grpc.(*Server).processStreamingRPC(0xc8200f0be0, 0x7f46a02823f0, 0xc8200714d0, 0xc82012e780, 0xc82011b440, 0xd53f00, 0x0, 0x0)
	/root/gofolder/src/google.golang.org/grpc/server.go:358 +0x3d5
google.golang.org/grpc.(*Server).handleStream(0xc8200f0be0, 0x7f46a02823f0, 0xc8200714d0, 0xc82012e780)
	/root/gofolder/src/google.golang.org/grpc/server.go:398 +0x7d4
google.golang.org/grpc.(*Server).Serve.func2.1(0xc82012e780)
	/root/gofolder/src/google.golang.org/grpc/server.go:228 +0x49
google.golang.org/grpc/transport.(*http2Server).operateHeaders.func3(0xc8201dec80, 0xc82012e780, 0xc8201fee60)
	/root/gofolder/src/google.golang.org/grpc/transport/http2_server.go:208 +0x26
created by google.golang.org/grpc/transport.(*http2Server).operateHeaders
	/root/gofolder/src/google.golang.org/grpc/transport/http2_server.go:210 +0xfe1
```

**Comment by ishidawataru** [comment]
Hi! Thanks for the report

Sould be fixed now. https://github.com/osrg/gobgp/commit/3313e8f8d63e0b502d6324d4d900f32776e11130

By the way, currently policy configuration is just enabled for route server clients.
(Definitely enabling policy configuration for normal peers is on the TODO list)

Please see https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md 
for how policy works in GoBGP.

**Comment by pavel-odintsov** [comment]
Thanks for fix and information. In current time I haven't any ability to specify community for announced perfix? Right?

**Comment by ishidawataru** [comment]
The answer is no when you use gobgp cli.
But gRPC API `ModPath` accepts any additional path attributes,
so you can append community to the announced routes.

**Comment by pavel-odintsov** [comment]
Thanks I will try to play with ModPath. So I have some troubles with gRPC now and asked about they in mail list.

Close this!
