### ISSUE TITLE
Segmentation fault with flow spec with source and destination ports

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#334]
Hello, folks!

```bash
gobgp global rib -a ipv4-flowspec del match destination 10.0.0.0/24 protocol tcp  destination-port 88 source-port 5353 source 20.0.0.0/24 then redirect 10:10
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/osrg/gobgp/packet.flowSpecNumericParser(0xc82018c040, 0x2, 0x6, 0x0, 0x0, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/packet/bgp.go:1934 +0x5e3
github.com/osrg/gobgp/packet.ParseFlowSpecComponents(0xc82001c300, 0x5c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/packet/bgp.go:2006 +0x548
github.com/osrg/gobgp/gobgp/cmd.ParseFlowSpecArgs(0xc820107200, 0xe, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/gofolder/src/github.com/osrg/gobgp/gobgp/cmd/global.go:213 +0x28a
github.com/osrg/gobgp/gobgp/cmd.ParsePath(0x10085, 0xc820107200, 0xe, 0x10, 0x0, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/gobgp/cmd/global.go:404 +0x1b05
github.com/osrg/gobgp/gobgp/cmd.modPath(0x0, 0x0, 0x0, 0xa01520, 0x3, 0xc820107200, 0xe, 0x10, 0x0, 0x0)
	/root/gofolder/src/github.com/osrg/gobgp/gobgp/cmd/global.go:453 +0xf8
github.com/osrg/gobgp/gobgp/cmd.NewGlobalCmd.func2(0xc82016a700, 0xc820107200, 0xe, 0x10)
	/root/gofolder/src/github.com/osrg/gobgp/gobgp/cmd/global.go:554 +0x87
github.com/spf13/cobra.(*Command).execute(0xc82016a700, 0xc820106f00, 0x10, 0x10, 0x0, 0x0)
	/root/gofolder/src/github.com/spf13/cobra/command.go:499 +0x869
github.com/spf13/cobra.(*Command).Execute(0xc82016a000, 0x0, 0x0)
	/root/gofolder/src/github.com/spf13/cobra/command.go:582 +0x46a
main.main()
	/root/gofolder/src/github.com/osrg/gobgp/gobgp/main.go:23 +0x25

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 3 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820182000)
	/root/gofolder/src/google.golang.org/grpc/transport/http2_client.go:799 +0x629
created by google.golang.org/grpc/transport.newHTTP2Client
	/root/gofolder/src/google.golang.org/grpc/transport/http2_client.go:193 +0x1536

goroutine 4 [IO wait]:
net.runtime_pollWait(0x7faedde86ad8, 0x72, 0xc82007c0b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820172680, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820172680, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820172620, 0xc82017e024, 0x9, 0x9, 0x0, 0x7faedde81028, 0xc82007c0b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200361a0, 0xc82017e024, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x7faee0ccc1b8, 0xc8200361a0, 0xc82017e024, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7faee0ccc1b8, 0xc8200361a0, 0xc82017e024, 0x9, 0x9, 0x3f33df36a0da9501, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
github.com/bradfitz/http2.readFrameHeader(0xc82017e024, 0x9, 0x9, 0x7faee0ccc1b8, 0xc8200361a0, 0xdd000000, 0xc800000000, 0x0, 0x0)
	/root/gofolder/src/github.com/bradfitz/http2/frame.go:228 +0xa5
github.com/bradfitz/http2.(*Framer).ReadFrame(0xc82017e000, 0x0, 0x0, 0x0, 0x0)
	/root/gofolder/src/github.com/bradfitz/http2/frame.go:373 +0xe6
google.golang.org/grpc/transport.(*framer).readFrame(0xc820132ed0, 0x0, 0x0, 0x0, 0x0)
	/root/gofolder/src/google.golang.org/grpc/transport/http_util.go:453 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc820182000)
	/root/gofolder/src/google.golang.org/grpc/transport/http2_client.go:729 +0x115
created by google.golang.org/grpc/transport.newHTTP2Client
	/root/gofolder/src/google.golang.org/grpc/transport/http2_client.go:199 +0x1595

goroutine 5 [select]:
google.golang.org/grpc.(*ClientConn).transportMonitor(0xc8200d1c30)
	/root/gofolder/src/google.golang.org/grpc/clientconn.go:383 +0x29a
created by google.golang.org/grpc.Dial
	/root/gofolder/src/google.golang.org/grpc/clientconn.go:188 +0x541

```

**Comment by pavel-odintsov** [comment]
So issue definitely related with source-port and destination-port.

**Comment by ishidawataru** [comment]
Hi!

`gobgp global rib -a ipv4-flowspec del match destination 10.0.0.0/24 protocol tcp  destination-port =88 source-port =5353 source 20.0.0.0/24 then redirect 10:10`
This sould work ('=' inserted).

However it's definiely not good that cli die. I'll fix this and modify to change the syntax you tried shortly.

**Comment by ishidawataru** [comment]
think this fixes. please try. https://github.com/osrg/gobgp/commit/b610280192e89fbab5f996c6fa0baa152584f993

**Comment by pavel-odintsov** [comment]
Work well, thanks!

```bash
gobgp global rib -a ipv4-flowspec add match destination 10.0.0.0/24 protocol tcp  destination-port 88 source-port 5353 source 20.0.0.0/24 then redirect 10:10
```

Result:
```bash
gobgp global rib -a ipv4-flowspec
    Network                                                                                                 Next Hop             AS_PATH              Age        Attrs
*>  [destination:10.0.0.0/24][protocol: tcp][destination-port: =88][source-port: =5353][source:20.0.0.0/24] fictitious                                00:00:02   [{Origin: i} {Extcomms: [redirect: 10:10]}]
```
