### ISSUE TITLE
gobgp crash panic: runtime error: index out of range

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#786]
Hello!

I'm sending own made flow spec to GoBGP's gRPC API and got following fault:
```bash
{"level":"debug","msg":"computeKnownBestPath known pathlist: 1","time":"2016-03-18T16:49:09Z"}
{"Data":{"IsWithdraw":false},"Key":"10.30.80.1","Topic":"Peer","level":"debug","msg":"From same AS, ignore.","time":"2016-03-18T16:49:09Z"}
{"Key":"10.30.80.1","State":5,"Topic":"Peer","data":{"Header":{"Marker":null,"Len":19,"Type":4},"Body":{}},"level":"debug","msg":"sent","time":"2016-03-18T16:49:39Z"}
panic: runtime error: index out of range
```

And more debug details:
```bash
goroutine 4 [running]:
panic(0xbe9580, 0xc820012020)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/osrg/gobgp/packet.formatFragment(0x80, 0x0, 0x0, 0x0)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/packet/bgp.go:2695 +0x8e0
github.com/osrg/gobgp/packet.(*FlowSpecComponent).String(0xc820328f40, 0x0, 0x0)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/packet/bgp.go:2721 +0x20d
github.com/osrg/gobgp/packet.(*FlowSpecNLRI).String(0xc820328da0, 0x0, 0x0)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/packet/bgp.go:2878 +0x16b
github.com/osrg/gobgp/table.(*Table).tableKey(0xc820254930, 0x7f2ae8fde6c8, 0xc820328da0, 0x0, 0x0)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/table/table.go:211 +0x33
github.com/osrg/gobgp/table.(*Table).getOrCreateDest(0xc820254930, 0x7f2ae8fde6c8, 0xc820328da0, 0x40ff57)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/table/table.go:177 +0x4a
github.com/osrg/gobgp/table.(*Table).insert(0xc820254930, 0xc820326840, 0x10085)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/table/table.go:41 +0x69
github.com/osrg/gobgp/table.(*TableManager).ProcessPaths(0xc8201c3880, 0xc82014a780, 0x1, 0x1, 0x0, 0x0, 0x0)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/table/table_manager.go:247 +0x223
github.com/osrg/gobgp/server.(*BgpServer).propagateUpdate(0xc8201e0000, 0x0, 0xc82014a780, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/server/server.go:901 +0xfad
github.com/osrg/gobgp/server.(*BgpServer).handleGrpc(0xc8201e0000, 0xc82032c320, 0x0, 0x0, 0x0)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/server/server.go:1860 +0x70aa
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc8201e0000)
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/server/server.go:481 +0x2d34
created by main.main
        /tmp/library_builder_folder/gobgp.build.dir.sBkmEPRfWr/gofolder/src/github.com/osrg/gobgp/gobgpd/main.go:188 +0xe86

```

**Comment by pavel-odintsov** [comment]
I've tried to announce following announce (that's is our pseudo format for encode json):
```bash
{ "source_prefix": "4.0.0.0/30", "destination_prefix": "5.5.5.5/32", "destination_ports": [ 80, 179 ], "source_ports": [ 53, 5353, 80, 15 ], "packet_lengths": [ 777, 1122, 70, 100 ], "protocols": [ "tcp", "udp" ], "fragmentation_flags": [ "is-fragment", "dont-fragment", "first-fragment", "last-fragment", "not-a-fragment" ], "tcp_flags": [ "syn" ], "action_type": "rate-limit", "action": { "rate": 1024 } }
```

And this:
```bash
{ "source_prefix": "4.0.0.0/30", "destination_prefix": "5.5.5.5/32", "destination_ports": [ 80, 179 ], "source_ports": [ 53, 5353, 80, 15 ], "packet_lengths": [ 777, 1122, 70, 100 ], "protocols": [ "tcp", "udp", "icmp" ], "fragmentation_flags": [ "is-fragment", "dont-fragment", "first-fragment", "last-fragment", "not-a-fragment" ], "tcp_flags": [ "syn", "ack", "fin", "urgent", "push", "rst" ], "action_type": "rate-limit", "action": { "rate": 1024 } }
```

**Comment by pavel-odintsov** [comment]
Looks like fault located inside fragment formatting code: https://github.com/osrg/gobgp/blob/master/packet/bgp.go#L2678

**Comment by fujita** [comment]
Thanks for the report. Looks like that the problem is that gobgp doesn't support "not-a-fragment" type (zero value). Should be fixed by https://github.com/osrg/gobgp/commit/66ac5a1051267c5d915461a2556ef33e8ac9e670

Can you try the latest?

**Comment by pavel-odintsov** [comment]
That's awesome fix and awesome fix speed! Never saw anything like this before! Will check as soon as possible.

**Comment by pavel-odintsov** [comment]
Working prefect!
