### ISSUE TITLE
gobgpd panics when adding and deleting a vrf

### ISSUE THREAD

**Issue by bryanschwerer** [osrg/gobgp#888]
Steps to reproduce

1. Start gogdpd (running as root) "./gobgpd -f bgpd.conf"
2. Add vrf  " ./gobgp vrf add vrf1 rd 100:100 rt  both 100:100"
3. Delete vrf "./gobgp vrf del vrf1"

config file 

```
[global.config]
  as = 65001
  router-id = "10.64.156.70"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.64.156.118"
    peer-as = 65001
  [[neighbors.afi-safis]]
      [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.11.13.86"
    peer-as = 65001
  [[neighbors.afi-safis]]
      [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"

```

This causes gobgpd to panic.  Stack trace

```
panic: assignment to entry in nil map

goroutine 12 [running]:
github.com/osrg/gobgp/table.(*AdjRib).Update(0xc820175c20, 0xc8200268a0, 0x1, 0x1)
	/home/bryans/code/src/github.com/osrg/gobgp/table/adj.go:74 +0x6a9
github.com/osrg/gobgp/server.(*Peer).processOutgoingPaths(0xc8200fde00, 0xc820026890, 0x1, 0x1, 0xc820026878, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/peer.go:193 +0x662
github.com/osrg/gobgp/server.(*BgpServer).propagateUpdate(0xc82008a800, 0x0, 0xc820026860, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:702 +0xb64
github.com/osrg/gobgp/server.(*BgpServer).handleGrpc(0xc82008a800, 0xc82022ea00, 0x0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:2259 +0x7cc2
github.com/osrg/gobgp/server.(*BgpServer).Serve(0xc82008a800)
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:339 +0xcb1
created by main.main
	/home/bryans/code/src/github.com/osrg/gobgp/gobgpd/main.go:174 +0xb76

goroutine 1 [select]:
main.main()
	/home/bryans/code/src/github.com/osrg/gobgp/gobgpd/main.go:198 +0x2bd1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 16 [chan receive]:
github.com/osrg/gobgp/server.(*BgpServer).Serve.func1(0xc820188b40)
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:212 +0x56
created by github.com/osrg/gobgp/server.(*BgpServer).Serve
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:217 +0xef

goroutine 15 [select]:
github.com/osrg/gobgp/server.(*grpcIncomingWatcher).loop(0xc820188a20, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/monitor.go:65 +0x99f
github.com/osrg/gobgp/server.(*grpcIncomingWatcher).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/monitor.go:119 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820188a20, 0xc8201858d0)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 10 [select, locked to thread]:
runtime.gopark(0xe57428, 0xc820025728, 0xccc9d8, 0x6, 0x432018, 0x2)
	/usr/lib/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820025728, 0x0, 0x18)
	/usr/lib/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820025728)
	/usr/lib/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/lib/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7ffff6fc4d20, 0x72, 0xc8200101e0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820176530, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820176530, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201764d0, 0x0, 0x7ffff6fc4e18, 0xc820175a20)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026588, 0xc820047d80, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820026588, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820188900, 0x7ffff6fc4de0, 0xc820026588, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820188900, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xce27f0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1967 +0x8f
main.main.func1()
	/home/bryans/code/src/github.com/osrg/gobgp/gobgpd/main.go:72 +0x3c
created by main.main
	/home/bryans/code/src/github.com/osrg/gobgp/gobgpd/main.go:73 +0x2d6

goroutine 13 [IO wait]:
net.runtime_pollWait(0x7ffff6fc4ae0, 0x72, 0xc8200101e0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820176bc0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820176bc0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820176b60, 0x0, 0x7ffff6fc4e18, 0xc820237560)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026658, 0xc820037d98, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820026658, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc820070990, 0x7ffff6fc3d78, 0xc820026658, 0x0, 0x0)
	/home/bryans/code/src/google.golang.org/grpc/server.go:277 +0x1b5
github.com/osrg/gobgp/server.(*Server).Serve(0xc820129260, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/grpc_server.go:95 +0x2d0
main.main.func2(0xc820129260)
	/home/bryans/code/src/github.com/osrg/gobgp/gobgpd/main.go:179 +0x25
created by main.main
	/home/bryans/code/src/github.com/osrg/gobgp/gobgpd/main.go:182 +0xbcd

goroutine 14 [chan receive]:
github.com/osrg/gobgp/config.ReadConfigfileServe(0x7fffffffe83c, 0x9, 0xe0cc9e, 0x4, 0xc8200188a0)
	/home/bryans/code/src/github.com/osrg/gobgp/config/serve.go:48 +0xc87
created by main.main
	/home/bryans/code/src/github.com/osrg/gobgp/gobgpd/main.go:193 +0x2c6c

goroutine 18 [chan receive]:
github.com/osrg/gobgp/server.(*BgpServer).Serve.func2(0xc820188ba0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:222 +0x43
created by github.com/osrg/gobgp/server.(*BgpServer).Serve
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:225 +0x12f

goroutine 19 [select]:
github.com/eapache/channels.(*InfiniteChannel).infiniteBuffer(0xc820175a40)
	/home/bryans/code/src/github.com/eapache/channels/infinite_channel.go:49 +0x29d
created by github.com/eapache/channels.NewInfiniteChannel
	/home/bryans/code/src/github.com/eapache/channels/infinite_channel.go:19 +0x1d1

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7ffff6fc4c60, 0x72, 0xc8200101e0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201765a0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201765a0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820176540, 0x0, 0x7ffff6fc4e18, 0xc820236d80)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026590, 0xc820188d80, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/osrg/gobgp/server.NewTCPListener.func1(0xc820026590, 0xc820188de0, 0xc820188d80, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:129 +0x37
created by github.com/osrg/gobgp/server.NewTCPListener
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:137 +0x3a5

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7ffff6fc4ba0, 0x72, 0xc8200101e0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820176610, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820176610, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201765b0, 0x0, 0x7ffff6fc4e18, 0xc820175ee0)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026598, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/osrg/gobgp/server.NewTCPListener.func1(0xc820026598, 0xc820188e40, 0xc820188d80, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:129 +0x37
created by github.com/osrg/gobgp/server.NewTCPListener
	/home/bryans/code/src/github.com/osrg/gobgp/server/server.go:137 +0x3a5

goroutine 23 [select]:
github.com/osrg/gobgp/server.(*FSM).connectLoop(0xc8200efee0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:361 +0x5ce
github.com/osrg/gobgp/server.(*FSM).(github.com/osrg/gobgp/server.connectLoop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:231 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8200efee0, 0xc820185d90)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 56 [chan receive]:
github.com/osrg/gobgp/server.(*FSMHandler).loop(0xc820262300, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1243 +0x163
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:400 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8200efee0, 0xc82026a180)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 25 [select]:
github.com/osrg/gobgp/server.(*FSM).connectLoop(0xc8202201a0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:361 +0x5ce
github.com/osrg/gobgp/server.(*FSM).(github.com/osrg/gobgp/server.connectLoop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:231 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8202201a0, 0xc8202220e0)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 41 [chan receive]:
github.com/osrg/gobgp/server.(*FSMHandler).loop(0xc82007fd80, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1243 +0x163
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.loop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:400 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc8202201a0, 0xc820222b80)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 57 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).established(0xc820262300, 0x100020000, 0x52702e)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1162 +0x14c9
github.com/osrg/gobgp/server.(*FSMHandler).loop.func1(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1234 +0x114
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820262300, 0xc820237200)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 42 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).established(0xc82007fd80, 0x200010000, 0x52702e)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1162 +0x14c9
github.com/osrg/gobgp/server.(*FSMHandler).loop.func1(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1234 +0x114
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82007fd80, 0xc8202365e0)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 43 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).sendMessageloop(0xc82007fd80, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1092 +0x667
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.sendMessageloop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1148 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82007fd80, 0xc820222d00)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 44 [IO wait]:
net.runtime_pollWait(0x7ffff6fc4a20, 0x72, 0xc8200101e0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820176ed0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820176ed0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820176e70, 0xc820237540, 0x13, 0x13, 0x0, 0x7ffff6fbe050, 0xc8200101e0)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026670, 0xc820237540, 0x13, 0x13, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x7ffff6fc5148, 0xc820026670, 0xc820237540, 0x13, 0x13, 0x13, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7ffff6fc5148, 0xc820026670, 0xc820237540, 0x13, 0x13, 0x13, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:316 +0x62
github.com/osrg/gobgp/server.readAll(0x7ffff6fc5090, 0xc820026670, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:569 +0xd9
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageWithError(0xc82007fd80, 0x0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:585 +0xa7
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageloop(0xc82007fd80, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1135 +0x31
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.recvMessageloop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1150 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc82007fd80, 0xc820222d10)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 59 [IO wait]:
net.runtime_pollWait(0x7ffff6fc4960, 0x72, 0xc8200101e0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820177d40, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820177d40, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820177ce0, 0xc820237300, 0x13, 0x13, 0x0, 0x7ffff6fbe050, 0xc8200101e0)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026778, 0xc820237300, 0x13, 0x13, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x7ffff6fc5148, 0xc820026778, 0xc820237300, 0x13, 0x13, 0x13, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7ffff6fc5148, 0xc820026778, 0xc820237300, 0x13, 0x13, 0x13, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:316 +0x62
github.com/osrg/gobgp/server.readAll(0x7ffff6fc5090, 0xc820026778, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:569 +0xd9
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageWithError(0xc820262300, 0xc820188c00, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:585 +0xa7
github.com/osrg/gobgp/server.(*FSMHandler).recvMessageloop(0xc820262300, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1135 +0x31
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.recvMessageloop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1150 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820262300, 0xc82026a310)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 58 [select]:
github.com/osrg/gobgp/server.(*FSMHandler).sendMessageloop(0xc820262300, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1092 +0x667
github.com/osrg/gobgp/server.(*FSMHandler).(github.com/osrg/gobgp/server.sendMessageloop)-fm(0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/fsm.go:1148 +0x2e
gopkg.in/tomb%2ev2.(*Tomb).run(0xc820262300, 0xc82026a300)
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:153 +0x21
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/home/bryans/code/src/gopkg.in/tomb.v2/tomb.go:149 +0x131

goroutine 60 [IO wait]:
net.runtime_pollWait(0x7ffff6fc48a0, 0x72, 0xc8200101e0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202644c0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202644c0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820264460, 0xc82026e000, 0x8000, 0x8000, 0x0, 0x7ffff6fbe050, 0xc8200101e0)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026850, 0xc82026e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820245c80)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820245c80, 0xc82015e938, 0x9, 0x9, 0xc81ffedc24, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7ffff6fc55d0, 0xc820245c80, 0xc82015e938, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7ffff6fc55d0, 0xc820245c80, 0xc82015e938, 0x9, 0x9, 0xc8ffffffff, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:316 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82015e938, 0x9, 0x9, 0x7ffff6fc55d0, 0xc820245c80, 0x20000000, 0x0, 0x0, 0x0)
	/home/bryans/code/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82015e900, 0x0, 0x0, 0x0, 0x0)
	/home/bryans/code/src/golang.org/x/net/http2/frame.go:463 +0x115
google.golang.org/grpc/transport.(*framer).readFrame(0xc820247860, 0x0, 0x0, 0x0, 0x0)
	/home/bryans/code/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820071560, 0xc8202478f0)
	/home/bryans/code/src/google.golang.org/grpc/transport/http2_server.go:243 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc820070990, 0x7ffff6fc5648, 0xc820071560)
	/home/bryans/code/src/google.golang.org/grpc/server.go:350 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc820070990, 0x7ffff6fc5090, 0xc820026850, 0x0, 0x0)
	/home/bryans/code/src/google.golang.org/grpc/server.go:337 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc820070990, 0x7ffff6fc5090, 0xc820026850)
	/home/bryans/code/src/google.golang.org/grpc/server.go:314 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/home/bryans/code/src/google.golang.org/grpc/server.go:286 +0x372

goroutine 61 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc820071560)
	/home/bryans/code/src/google.golang.org/grpc/transport/http2_server.go:647 +0x5d8
created by google.golang.org/grpc/transport.newHTTP2Server
	/home/bryans/code/src/google.golang.org/grpc/transport/http2_server.go:134 +0x84e

goroutine 62 [runnable]:
github.com/osrg/gobgp/server.(*Server).mod(0xc820129260, 0x20, 0xc2cba0, 0xc82026ab70, 0x414100, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/grpc_server.go:357 +0x1fb
github.com/osrg/gobgp/server.(*Server).ModVrf(0xc820129260, 0x7ffff6fc5888, 0xc820247aa0, 0xc82026ab70, 0xc82026ab60, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/server/grpc_server.go:365 +0x59
github.com/osrg/gobgp/api._GobgpApi_ModVrf_Handler(0xcb5420, 0xc820129260, 0x7ffff6fc5888, 0xc820247aa0, 0xc820266800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bryans/code/src/github.com/osrg/gobgp/api/gobgp.pb.go:2664 +0x16b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc820070990, 0x7ffff6fc5648, 0xc820071560, 0xc8200e0a80, 0xc820129280, 0x10d5460, 0x0, 0x0, 0x0)
	/home/bryans/code/src/google.golang.org/grpc/server.go:522 +0xe30
google.golang.org/grpc.(*Server).handleStream(0xc820070990, 0x7ffff6fc5648, 0xc820071560, 0xc8200e0a80, 0x0)
	/home/bryans/code/src/google.golang.org/grpc/server.go:682 +0x109d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc82026aa70, 0xc820070990, 0x7ffff6fc5648, 0xc820071560, 0xc8200e0a80)
	/home/bryans/code/src/google.golang.org/grpc/server.go:348 +0xa0
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/bryans/code/src/google.golang.org/grpc/server.go:349 +0x9a
```

**Comment by fujita** [comment]
Should be fixed by https://github.com/osrg/gobgp/commit/58bff63736bb058df44064bff3cb443e2675befb

Can you try the latest?

**Comment by bryanschwerer** [comment]
Yes, it works.

Thx
